import { T_fileTypes } from "@typesDef/types";
import { ReactNode } from "react";
import { MdOutlineAudioFile } from "react-icons/md";
import { GoFileZip } from "react-icons/go";
import { IoDocumentTextOutline } from "react-icons/io5";
import { FaRegFileImage } from "react-icons/fa6";
import { FaRegFileVideo } from "react-icons/fa";
import { FaRegFileCode } from "react-icons/fa6";

export const filesExtentionCategories: Record<T_fileTypes, string[]> = {
  doc: [
    "doc",
    "docx",
    "pdf",
    "txt",
    "rtf",
    "odt",
    "html",
    "htm",
    "xml",
    "md",
    "ppt",
    "pptx",
    "xls",
    "xlsx",
    "csv",
  ],
  image: [
    "jpg",
    "jpeg",
    "png",
    "gif",
    "bmp",
    "tiff",
    "svg",
    "webp",
    "ico",
    "heic",
    "raw",
    "avif",
  ],
  video: [
    "mp4",
    "avi",
    "mov",
    "wmv",
    "flv",
    "mkv",
    "webm",
    "mpeg",
    "mpg",
    "3gp",
    "m4v",
  ],
  audio: ["mp3", "wav", "aac", "flac", "ogg", "m4a", "wma", "aiff"],
  compressed: ["zip", "rar", "7z", "tar", "gz", "bz2", "xz"],
  webExtentions: [
    "gitignore",
    "json",
    "html",
    "htm",
    "css",
    "js",
    "php",
    "asp",
    "aspx",
    "jsp",
    "sql",
    "cpp",
    ".js",
    ".ts",
    ".py",
    ".java",
    ".cpp",
    ".c",
    ".cs",
    ".rb",
    ".php",
    ".swift",
    ".go",
    ".rs",
    ".kt",
    ".m",
    ".pl",
    ".r",
    ".sh",
    ".sql",
    ".html",
    ".css",
    ".xml",
    ".json",
    ".yaml",
    ".toml",
  ],
};

export const FileTypeIcons: Record<T_fileTypes, ReactNode> = {
  audio: <MdOutlineAudioFile size={22} />,
  compressed: <GoFileZip size={22} />,
  doc: <IoDocumentTextOutline size={22} />,
  image: <FaRegFileImage size={22} />,
  video: <FaRegFileVideo size={22} />,
  webExtentions: <FaRegFileCode size={22} />,
};
